server:
  port: 9999
  context-path: /uaa

myapp:
  client:
    name: myapp
    secret: myapps3cr3t
    scope: myapp
  keystore:
    name: myapp.jks
    pass: myapp@uthk3y5tor3
  key:
    name: myappkey
    pass: myapp@uthk3y
  ldap:
    url: "ldap://127.0.0.1:389"
    ldif: "classpath:test.ldif"
    manager-dn-patterns: "CN=multiplicaadmin,CN=Users,DC=dev,DC=multiplica,DC=com"
    manager-password:
    user-search-base:
    user-dn-patterns: "uid={0}, ou=people"
    group-search-base: "ou=groups"
    group-search-filter: "(uniqueMember={0})"
